items:
- name: Системные требования
  href: system-requirements.md
- name: Способы развёртывания
  href: deployment-options/index.md
  include:
    mode: link
    path: deployment-options/toc_p.yaml
- name: Управление конфигурацией кластера
  href: configuration-management/index.md
  include:
    mode: link
    path: configuration-management/toc_p.yaml
- name: Наблюдаемость
  href: observability/index.md
  include:
    mode: link
    path: observability/toc_p.yaml
- name: Резервное копирование и восстановление
  href: backup-and-recovery.md
- name: Обслуживание кластера
  href: maintenance/index.md
  include:
    mode: link
    path: maintenance/toc_p.yaml
