name: Regression-whitelist-run

on:
  schedule:
    - cron: "0 23 * * *"  # At 23:00 every day
  workflow_dispatch:

jobs:
  ya_x86_64:
    name: Regression-run
    uses: ./.github/workflows/run_all_tests.yml
    secrets: inherit
    with:
      test_targets: ydb/tests/sql/ ydb/tests/stress ydb/tests/functional/tpc ydb/tests/functional/benchmarks_init

