name: Regression-whitelist-run

on:
  schedule:
    - cron: "0 23 * * *"  # At 23:00 every day
  workflow_dispatch:

jobs:
  main
    name: Regression-run
    uses: ./.github/workflows/run_all_tests.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix: 
         build_preset: ["relwithdebinfo", "release-asan", "release-tsan", "release-msan"]
    with:
      runner_label: self-hosted
      test_targets: ydb/tests/sql/ ydb/tests/stress ydb/tests/functional/tpc ydb/tests/functional/benchmarks_init
      build_preset: ${{ matrix.build_preset }}

