name: Regression-run

on:
  schedule:
    - cron: "0 1 * * *"  # At 01:00 every day
  workflow_dispatch:

jobs:
  run_all_tests:
    name: TEST ${{ github.ref_name }}:${{ matrix.build_preset }}
    runs-on: [self-hosted, "${{ inputs.runner_label || 'auto-provisioned' }}", "${{ format('build-preset-{0}', inputs.build_preset || 'relwithdebinfo') }}"]
    timeout-minutes: 600
    env:
      BUILD_TARGETS_JSON: '["ydb"]'
      TEST_SIZE: small,medium,large
      TEST_TYPE: unittest,py3test,py2test,pytest

    strategy:
      fail-fast: false
      matrix:
        build_preset: [relwithdebinfo, release-asan, release-msan, release-tsan] # list of build presets to run
        include:
          - build_preset: relwithdebinfo
            threads_count: 52
            timeout: 300
          - build_preset: release-asan
            threads_count: 20
            timeout: 480
          - build_preset: release-msan
            threads_count: 20
            timeout: 480
          - build_preset: release-tsan
            threads_count: 10
            timeout: 600

    steps:
      - name: Run YDB Tests
        uses: ./.github/workflows/run_all_tests.yml
        with:
          runner_label: ${{ inputs.runner_label }}
          build_preset: ${{ matrix.build_preset }}
          branch: ${{ github.ref_name }} 
          threads_count: ${{ matrix.threads_count }}
          timeout: ${{ matrix.timeout }}
          test_size:  ${{ env.TEST_SIZE }}
          test_type: ${{ env.TEST_TYPE }}
