name: Regression-whitelist-run

on:
  schedule:
    - cron: "0 23 * * *"  # At 23:00 every day
  workflow_dispatch:

jobs:
  ya_x86_64:
    name: Regression-run
    runs-on: [ self-hosted, "${{ inputs.runner_label || 'auto-provisioned' }}", "${{ format('build-preset-{0}', matrix.build_preset || 'relwithdebinfo') }}" ]
    timeout-minutes: 600
    uses: ./.github/workflows/run_all_tests.yml
    secrets: inherit
    strategy:
      matrix: ["relwithdebinfo", "release-asan", "release-tsan", "release-msan"]
      fail-fast: false
    with:
      test_targets: ydb/tests/sql/ ydb/tests/stress ydb/tests/functional/tpc ydb/tests/functional/benchmarks_init

