name: Regression-run

on:
  schedule:
    - cron: "0 1 * * *"  # At 01:00 every day
  workflow_dispatch:

jobs:
  run_all_tests:
    name: TEST ${{ github.ref_name }}:${{ matrix.build_preset }}
    runs-on: [self-hosted, "${{ inputs.runner_label || 'auto-provisioned' }}", "${{ format('build-preset-{0}', inputs.build_preset || 'relwithdebinfo') }}"]
    timeout-minutes: 600
    env:
      TEST_TARGETS: 'ydb/'
      TEST_SIZE: small,medium,large
      TEST_TYPE: unittest,py3test,py2test,pytest

    strategy:
      fail-fast: false
      matrix:
        build_preset: [relwithdebinfo, release-asan, release-msan, release-tsan]
        include:
          - build_preset: relwithdebinfo
            threads_count: 52
            timeout: 300
          - build_preset: release-asan
            threads_count: 20
            timeout: 480
          - build_preset: release-msan
            threads_count: 20
            timeout: 480
          - build_preset: release-tsan
            threads_count: 10
            timeout: 600

    steps:
      - name: Run YDB Tests ${{ github.ref_name }} 
        timeout-minutes: ${{ matrix.timeout }}
        uses: ./.github/workflows/build_and_test_ya.yml
        with:
          build_target: ${{ env.TEST_TARGETS }}
          runner_label: ${{ inputs.runner_label }}
          build_preset: ${{ matrix.build_preset }}
          test_threads: ${{ matrix.threads_count }}
          test_size:  ${{ env.TEST_SIZE }}
          test_type: ${{ env.TEST_TYPE }}
          additional_ya_make_args: -DDEBUGINFO_LINES_ONLY
          test_retry_count: 3
