name: Regression-whitelist-run

on:
  schedule:
    - cron: "0 23 * * *"  # Every day at 23:00
  workflow_dispatch:

jobs:
  run_all_tests:
    name: TEST ${{ github.ref_name }}:${{ matrix.build_preset }}
    runs-on: [self-hosted, "${{ inputs.runner_label || 'auto-provisioned' }}", "${{ format('build-preset-{0}', inputs.build_preset || 'relwithdebinfo') }}"]
    env:
      TEST_TARGETS: "ydb/tests/sql/ ydb/tests/stress ydb/tests/functional/tpc ydb/tests/functional/benchmarks_init"
      TEST_SIZE: small,medium,large
      TEST_TYPE: unittest,py3test,py2test,pytest

    strategy:
      fail-fast: false
      matrix:
        build_preset: [relwithdebinfo, release-asan, release-msan, release-tsan]
        include:
          - build_preset: relwithdebinfo
            threads_count: 52
            timeout: 300
          - build_preset: release-asan
            threads_count: 20
            timeout: 480
          - build_preset: release-msan
            threads_count: 20
            timeout: 480
          - build_preset: release-tsan
            threads_count: 10
            timeout: 600
            timeout-minutes: ${{ matrix.timeout }}
    uses: ./.github/workflows/build_and_test_ya.yml
    with:
      runner_additional_label: ${{ format('build-preset-{0}', matrix.build_preset) }}
      build_target: ${{ env.TEST_TARGETS }}
      runner_label: ${{ inputs.runner_label }}
      build_preset: ${{ matrix.build_preset }}
      test_threads: ${{ matrix.threads_count }}
      test_size:  ${{ env.TEST_SIZE }}
      test_type: ${{ env.TEST_TYPE }}
      commit_sha: ${{ github.ref_name }}
      additional_ya_make_args: -DDEBUGINFO_LINES_ONLY
      test_retry_count: 3
    secrets: inherit


