name: Regression-run

on:
  schedule:
    - cron: "0 1 * * *"  # At 01:00 every day
  workflow_dispatch:

jobs:
  main:
    name: Regression-run
    uses: ./.github/workflows/run_tests.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix: 
         build_preset: ["relwithdebinfo", "release-asan", "release-tsan", "release-msan"]
    with:
      runner_label: self-hosted
      test_targets: ydb/
      build_preset: ${{ matrix.build_preset }}

