name: Regression-run

on:
  schedule:
    - cron: "0 1 * * *"  # At 01:00 every day
  workflow_dispatch:

jobs:
  ya_x86_64:
    name: Regression-run
    uses: ./.github/workflows/run_all_tests.yml
    secrets: inherit
    with:
      build_target: ydb/

