name: Run all tests

on:
  workflow_call:
    inputs:
      test_targets:
        description: 'Пути запуска'
        required: true
        type: string
        default: ydb/
      test_type:
        description: 'Тип тестов'
        required: false
        type: string
        default: unittest,py3test,py2test,pytest
      test_size:
        description: 'Размер тестов'
        required: false
        type: string
        default: small,medium,large
      additional_ya_make_args:
        description: 'Дополнительные аргументы для ya make'
        required: false
        type: string
        default: -DDEBUGINFO_LINES_ONLY

jobs:
  run_all_tests:
    name: Test ${{ github.ref_name }}:${{ matrix.build_preset }}
    runs-on: [ self-hosted, "${{ inputs.runner_label || 'auto-provisioned' }}", "${{ format('build-preset-{0}', inputs.build_preset || 'relwithdebinfo') }}"]
    timeout-minutes: 600

    strategy:
      fail-fast: false
      matrix:
        build_preset: [relwithdebinfo, release-asan, release-msan, release-tsan]
        include:
          - build_preset: relwithdebinfo
            threads_count: 52
            timeout: 300
          - build_preset: release-asan
            threads_count: 20
            timeout: 480
          - build_preset: release-msan
            threads_count: 20
            timeout: 480
          - build_preset: release-tsan
            threads_count: 10
            timeout: 600

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Run YDB Tests ${{ github.ref_name }}
        timeout-minutes: ${{ matrix.timeout }}
        uses: ./.github/workflows/build_and_test_ya_provisioned.yml
        with:
          commit_sha: ${{ github.ref_name }}
          build_preset: ${{ matrix.build_preset }}
          increment: false
          build_target: ${{ inputs.test_targets }}
          run_build: true
          run_tests: true
          test_retry_count: 3
          test_size: ${{ inputs.test_size }}
          test_type: ${{ inputs.test_type }}
          test_threads: ${{ matrix.threads_count }}
          put_build_results_to_cache: true
          additional_ya_make_args: ${{ inputs.additional_ya_make_args }}
          secs: ${{ format('{{"TESTMO_TOKEN2":"{0}","AWS_KEY_ID":"{1}","AWS_KEY_VALUE":"{2}","REMOTE_CACHE_USERNAME":"{3}","REMOTE_CACHE_PASSWORD":"{4}"}}',
            secrets.TESTMO_TOKEN2, secrets.AWS_KEY_ID, secrets.AWS_KEY_VALUE, secrets.REMOTE_CACHE_USERNAME, secrets.REMOTE_CACHE_PASSWORD ) }}
          vars: ${{ format('{{"AWS_BUCKET":"{0}","AWS_ENDPOINT":"{1}","REMOTE_CACHE_URL":"{2}","TESTMO_URL":"{3}","TESTMO_PROJECT_ID":"{4}"}}',
            vars.AWS_BUCKET, vars.AWS_ENDPOINT, vars.REMOTE_CACHE_URL_YA, vars.TESTMO_URL, vars.TESTMO_PROJECT_ID ) }}